GET http://localhost:3003/
###create user
POST  http://localhost:3003/user/singup
content-type: application/json

{
    "name": "jr P",
    "email": "juniorcvnnn@gmail.com",
    "password":"hakunabatata"
}
###login user
POST  http://localhost:3003/user/login
content-type: application/json

{
    "email": "juniorcvnnn@gmail.com",
    "password":"hakunabatata"
}

### create character
POST  http://localhost:3003/character/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiZWRkMDNkLTYwOTQtNDI3NS1hNzkzLWM2OGFjNzYyZTg3YiIsImlhdCI6MTY4MzU2NzIzOSwiZXhwIjoxNjgzNjUzNjM5fQ.TsVX2NvYn5hvZC8K6FA8n9FWJH47aDDEkFtXYn6RCTw
content-type: application/json

{
    "name":"Timão",
    "species":"Animal",
    "image":"https://garotasgeeks.com/wp-content/uploads/2011/05/tim%C3%A3o.jpg"
}

### all characters
GET  http://localhost:3003/character/all-characters
